name: Meu Workflow Automático

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  executar-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Rodar script personalizado
        run: bash ./meu_script.sh
